name: Documentation
# Generates and Deploys doxygen docs
on:
  push:
    branches: [ main ] # only gen docs for pushes to main
    paths:
    - 'include/*'
    - 'docs/*'
    - 'README.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # creates a dist/documentation/* folder containing the html documentation
  deploy-local: 
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: docs/Doxyfile
    - name: Upload Documentation Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aurora-documentation
        path: dist/documentation/
        if-no-files-found: error
    - name: deploy web
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/documentation/html
