name: Build All

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '15.3.Rel1'
    - name: setup python
      uses: actions/setup-python@v7
      with:
        python-version: '3.11.16'
    - name: Validate Builds
      run: ./ci/validate_build.sh

  dist:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '15.3.Rel1'
    - name: setup python
      uses: actions/setup-python@v7
      with:
        python-version: '3.11.16'
    - name: Validate Builds
      run: ./ci/validate_build.sh
    - name: Create Distributable Binaries
      run: python ./ci/build_dist.py -ru
    - name: Upload Dist Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aurora-dist
        path: dist/
        if-no-files-found: error
